spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warenova_db
    username: postgres
    password: ShivamJha91
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    com.warenova.wms: DEBUG